config/routes.rb
Rails.application.routes.draw do
  root to: "lists#index"
  resources :lists do
    resources :tasks do
      member do
        patch :done
      end
    end
  end
end

app/models/list.rb
class List < ActiveRecord::Base
  has_many :tasks
  
  validates :name, :presence => true
  validates :description, :presence => true
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :list

  validates :description, :presence => true
  scope(:done, -> do
    where({done: true})
  end)
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
    render :index
  end

  def update
    @list= List.find(params[:id])
    if @list.update(list_params)
      redirect_to lists_path
    else
      render :edit
    end
  end

  def show
    @list = List.find(params[:id])
    render :show
  end

  def new
    @list = List.new
    render :new
  end

  def edit
    @list = List.find(params[:id])
    render :edit
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to lists_path
    else
      render :new
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path
  end

  private
  def list_params
    params.require(:list).permit(:name, :description)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @task = @list.tasks.new
  end

  def create
    @list = List.find(params[:list_id])
    @task = @list.tasks.new(task_params)
    if @task.save
      flash[:notice] = "Task successfully added!"
      redirect_to lists_path(@task.list)
    else
      render :new
    end
  end

  def destroy
    @list = List.find(params[:list_id])
    @task = @list.tasks.find(params[:id])
    @task.destroy
    redirect_to lists_path(@task.list)
  end

  def update
    @list= List.find(params[:list_id])
    @task = @list.tasks.find(params[:id])
    if @task.update(task_params)
      redirect_to lists_path(@task.list)
    else
      render :edit
    end
  end

  def edit
    @list = List.find(params[:list_id])
    @task = @list.tasks.find(params[:id])
    render :edit
  end

  def done
    @list = List.find(params[:list_id])
    @task = Task.find(params[:id])
    @task.update(done: true)
    redirect_to lists_path(@task.list)
  end

private
  def task_params
    params.require(:task).permit(:description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ToDo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/lists/_form.html.erb
<%= render "layouts/errors", :object => @list %>

<%= form_for @list do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.submit %>
<% end %>

app/views/lists/edit.html.erb
<h1>Edit List</h1>

<%= render "form" %>

app/views/lists/index.html.erb
<h1>Lists</h1>

<ul>
  <% @lists.each do |list| %>
    <li><%= link_to list.name, list_path(list) %></li>
  <% end %>
</ul>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= render "form" %>

app/views/lists/show.html.erb
<% content_for(:title, "List | To Do") %>

<h1><%= @list.name %></h1>

<% if @list.tasks.any? %>
  <h4>Here are the tasks for this list:</h4>

  <ul>
    <% @list.tasks.each do |task| %>
      <% unless task.done %>
        <li>
          <%= task.description %> |
          <%= link_to "Edit", edit_list_task_path(@list, task) %> |
          <%= link_to "Done", done_list_task_path(@list, task),
                                  :data =>{:confirm => "Are you done?",
                                            :method => "patch"} %> |

          <%= link_to "Delete", list_task_path(@list, task),
                                  :data =>{:confirm => "Are you sure?",
                                            :method => "delete"} %> |
        </li>
      <% end %>
    <% end %>
  </ul>
<% else %>
  <p>There are no tasks yet!</p>
<% end %>

<%if @list.tasks.any? %>
  <% if @list.tasks.done.any? %>
  <!-- used a scope in the model Task.. model is like the lib file -->
    <h4>Look at all you have accomplished</h4>
    <ul>
      <% @list.tasks.done.each do |task| %>
        <li><%=task.description %> |
          <%= link_to "Delete", list_task_path(@list, task),
                                :data =>{:confirm => "Are you sure?",
                                         :method => "delete"} %>

        </li>
      <% end %>
    </ul>
  <%else%>
    <h4> You have things to do. Get on it!</h4>
  <% end %>
<%end%>

<p><%= link_to "Add a task", new_list_task_path(@list) %></p>
<p><%= link_to "Delete List", list_path(@list),
                                :data => {:confirm => "You sure?",
                                          :method => "delete"} %></p>

<p><%= link_to "Return to lists", list_path %></p>

app/views/tasks/_form.html.erb
<%= render('layouts/errors', :object => @task) %>

<%= form_for [@list, @task] do |f| %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <p><%= f.submit %></p>
<% end %>

app/views/tasks/edit.html.erb
<h1>Edit List</h1>

<%= render "form" %>

app/views/tasks/new.html.erb
<% content_for(:title, "New task | To Do") %>

<h1>New task for <%= @list.name %></h1>

<%= render 'form' %>